apiVersion: v1
kind: Service
metadata:
  name: nexus-service
spec:
  selector:
    app: nexus # Traffic goes to pods with this label
  ports:
    - protocol: TCP
      port: 80 # Expose on port 80
      targetPort: 3000 # Forward to container port 3000
  type: ClusterIP # Traefik (Ingress) will route traffic to this internal service
